<footer id="footer" class="wrapperforfooter">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="https://www.khadas.com/" target="_blank">{{ config.author }}</a><br>
    </div>
    <div id="footer-links">
      <a href="https://facebook.com/{{ config.facebook }}" class="footer-link" target="_blank"><i class="fa fa-facebook"></i></a>
      <a href="https://twitter.com/{{ config.twitter }}" class="footer-link" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="https://youtube.com/c/{{ config.youtube }}" class="footer-link" target="_blank"><i class="fa fa-youtube-play"></i></a>
      <a href="https://github.com/{{ config.github }}" class="footer-link" target="_blank"><i class="fa fa-github-alt"></i></a>
    </div>
  </div>
</footer>
